import "./globals.css";
import { Mulish, Rokkitt } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mulish",
});

const rokkitt = Rokkitt({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rokkitt",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mulish.variable} ${rokkitt.variable}`}>
      <body>{children}</body>
    </html>
  );
}
