import "./globals.css";
import { Mulish, Rokkitt, Bai_Jamjuree } from "next/font/google";

const bai_jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bai-jamjuree",
  weight: ['400', '600'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mulish",
});

const rokkitt = Rokkitt({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rokkitt",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mulish.variable} ${rokkitt.variable} ${bai_jamjuree.variable}`}>
      <body>{children}</body>
    </html>
  );
}
